services:
  traefik:
    image: traefik:latest
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.email=${LETSENCRYPT_EMAIL}"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--serversTransport.insecureSkipVerify=false"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./letsencrypt:/letsencrypt
    networks:
      - krayin-traefik_web
      - krayin-traefik_internal

  krayin:
    image: webkul/krayin:2.0.1
    restart: unless-stopped
    depends_on:
      - krayin-mysql
    environment:
      # basic DB env for the app. The app may use ./app/.env — keep that in sync.
      DB_HOST: krayin-mysql
      DB_DATABASE: "${MYSQL_DATABASE}"
      DB_USERNAME: "${MYSQL_USER}"
      DB_PASSWORD: "${MYSQL_PASSWORD}"
      APP_ENV: production
      APP_DEBUG: "false"
    volumes:
      - ./app:/var/www/html:rw
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=krayin-traefik_web"
      - "traefik.http.routers.krayin-http.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.krayin-http.entrypoints=web"
      - "traefik.http.routers.krayin-http.middlewares=redirect-to-https@docker"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.routers.krayin.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.krayin.entrypoints=websecure"
      - "traefik.http.routers.krayin.tls=true"
      - "traefik.http.routers.krayin.tls.certresolver=le"
      - "traefik.http.services.krayin.loadbalancer.server.port=80"
    networks:
      - krayin-traefik_web
      - krayin-traefik_internal

  krayin-mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - krayin-traefik_internal

  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    environment:
      PMA_HOST: krayin-mysql
      PMA_USER: "${MYSQL_USER}"
      PMA_PASSWORD: "${MYSQL_PASSWORD}"
    ports:
      # bind to localhost only to avoid public exposure (change if you want external access)
      - "127.0.0.1:8082:80"
    depends_on:
      - krayin-mysql
    labels:
      - "traefik.enable=false"
    networks:
      - krayin-traefik_internal

networks:
  krayin-traefik_web:
    name: krayin-traefik_web
    driver: bridge
  krayin-traefik_internal:
    name: krayin-traefik_internal
    driver: bridge

volumes:
  db_data:
  # letsencrypt directory will be a bind-mount to ./letsencrypt on host
